package com.ooad.miniproject.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.util.List;

@Document(collection = "bookings")
public class Booking {
    @Id
    private String id; // Auto-generated by MongoDB if not set
    
    private String userId;      // Reference to the User who made the booking
    private List<String> ticketIds; // List of Ticket IDs included in this booking
    private double totalAmount; // Sum of all ticket prices

    // Default constructor (required by Spring Data)
    public Booking() {}

    // Parameterized constructor (optional)
    public Booking(String userId, List<String> ticketIds, double totalAmount) {
        this.userId = userId;
        this.ticketIds = ticketIds;
        this.totalAmount = totalAmount;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public List<String> getTicketIds() {
        return ticketIds;
    }

    public void setTicketIds(List<String> ticketIds) {
        this.ticketIds = ticketIds;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    // Optional: toString() for debugging
    @Override
    public String toString() {
        return "Booking{" +
                "id='" + id + '\'' +
                ", userId='" + userId + '\'' +
                ", ticketIds=" + ticketIds +
                ", totalAmount=" + totalAmount +
                '}';
    }
}