package com.ooad.miniproject.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.geo.GeoJsonPoint;

@Document(collection = "stations")
public class Station {
    @Id
    private String id; // Auto-generated by MongoDB
    
    private String code; // Unique station code (e.g., "DEL" for Delhi)
    private String name;
    private String city;
    private String state;
    private GeoJsonPoint location; // GeoJSON format for coordinates
    
    // Default constructor (required by Spring Data)
    public Station() {}

    // Parameterized constructor
    public Station(String code, String name, String city, String state, double longitude, double latitude) {
        this.code = code;
        this.name = name;
        this.city = city;
        this.state = state;
        this.location = new GeoJsonPoint(longitude, latitude);
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public GeoJsonPoint getLocation() {
        return location;
    }

    public void setLocation(double longitude, double latitude) {
        this.location = new GeoJsonPoint(longitude, latitude);
    }

    // toString() for debugging
    @Override
    public String toString() {
        return "Station{" +
                "id='" + id + '\'' +
                ", code='" + code + '\'' +
                ", name='" + name + '\'' +
                ", city='" + city + '\'' +
                ", state='" + state + '\'' +
                ", location=" + location +
                '}';
    }
}