package com.ooad.miniproject.models;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "tickets")
public class Ticket {
    @Id
    private String id; // Auto-generated by MongoDB

    private String userId;      // Who booked the ticket (not necessarily the passenger)
    private String trainId;     // Reference to Train document
    private String passengerName;
    private String seatClass;   // "first", "second", "sleeper", or "executive"
    private int seatNumber;     // Numbered seat in its class
    private String status;      // "PENDING", "APPROVED", or "INVALID"
    private double price;       // Ticket price

    // Default constructor (required by Spring Data)
    public Ticket() {}

    // Parameterized constructor (optional)
    public Ticket(String userId, String trainId, String passengerName, 
                 String seatClass, int seatNumber, String status, double price) {
        this.userId = userId;
        this.trainId = trainId;
        this.passengerName = passengerName;
        this.seatClass = seatClass;
        this.seatNumber = seatNumber;
        this.status = status;
        this.price = price;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getTrainId() {
        return trainId;
    }

    public void setTrainId(String trainId) {
        this.trainId = trainId;
    }

    public String getPassengerName() {
        return passengerName;
    }

    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }

    public String getSeatClass() {
        return seatClass;
    }

    public void setSeatClass(String seatClass) {
        this.seatClass = seatClass;
    }

    public int getSeatNumber() {
        return seatNumber;
    }

    public void setSeatNumber(int seatNumber) {
        this.seatNumber = seatNumber;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    // toString() for debugging (excludes sensitive fields)
    @Override
    public String toString() {
        return "Ticket{" +
                "id='" + id + '\'' +
                ", trainId='" + trainId + '\'' +
                ", passengerName='" + passengerName + '\'' +
                ", seatClass='" + seatClass + '\'' +
                ", seatNumber=" + seatNumber +
                ", status='" + status + '\'' +
                ", price=" + price +
                '}';
    }
}